name: homease
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  animated_splash_screen: ^1.3.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.1
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  device_preview: ^1.2.0
  firebase_database: ^11.3.5
  cloud_firestore: ^5.6.6
  geolocator: ^11.0.0
  geocoding: 3.0.0
  permission_handler: ^11.0.0
  intl_phone_field: ^3.2.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets  :
    -  assets/splash/image.png
    -  assets/splash/image.svg
    -  assets/splash/image 2.png
    -  assets/splash/image 2 (1).png
    -  assets/splash/IMG_0157 1.png
    -  assets/splash/image 3.png
    -  assets/splash/image 4.png
    -  assets/onboarding/Group 34487.png
    -  assets/onboarding/Group 34489 (2).png
    -  assets/onboarding/Group 34487 (1).png
    -  assets/onboarding/Group 34489 (3).png
    -  assets/onboarding/Group 34487 (2).png
    -  assets/onboarding/Group 34489 (1).png
    -  assets/onboarding/new_image.png
    -  assets/onboarding/new_image_2.png
    -  assets/onboarding/new_image_3.png
    -  assets/onboarding/image.svg
    -  assets/onboarding/image 2355.png
    -  assets/onboarding/Mask Group.png
    -  assets/onboarding/Frame 1.svg
    -  assets/onboarding/Frame 1 (1).svg
    -  assets/onboarding/apple.svg
    -  assets/onboarding/ic_baseline-apple.svg
    -  assets/onboarding/Address-amico 1.svg
    -  assets/onboarding/image 4.png
    -  assets/splash/home_logo.svg
    -  assets/svg_images/Group 34487.svg
    -  assets/svg_images/Group 34487_2.svg
    -  assets/svg_images/Group 34607.svg
    -  assets/svg_images/Group 34606.svg
    -  assets/svg_images/Group 34611.svg
    -  assets/svg_images/Group 34607.svg
    -  assets/svg_images/Group 34612.svg
    -  assets/svg_images/Group 34613.svg
